#!/usr/bin/env python3
"""Turns data/charts/*.json (the research, as retrieved) into supabase/seed/charts_draft.sql.

Every chart lands as a draft. Nothing is downloaded by the extension until a human flips a chart
to 'verified' in the Supabase dashboard. Chart ids are deterministic (uuid5 of brand, category,
fit line and source URL) so the file can be re-run after a correction without duplicating rows.
"""
import glob
import json
import os
import uuid

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'data', 'charts')
OUT = os.path.join(ROOT, 'supabase', 'seed', 'charts_draft.sql')
NS = uuid.UUID('6f1c6c6e-5b8d-4c1b-9a9e-2a2a0d0c0b01')

MEASURES = ('bust', 'waist', 'hip', 'inseam', 'foot_length')
# Rows the brand page gets visibly wrong. Kept exactly as published, flagged so the engine skips them.
SUSPECT = {
    ('rag-bone', 'jeans', None, '23'): 'Published as waist 32 cm; the inches table gives 24 in (61 cm). Brand-page typo.',
}


def lit(v):
    if v is None:
        return 'null'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def jsonb(v):
    return lit(json.dumps(v, ensure_ascii=False, separators=(',', ':'))) + '::jsonb'


def rng(v):
    if v is None:
        return 'null, null'
    lo, hi = (v if isinstance(v, (list, tuple)) else (v, v))
    return f'{lit(lo)}, {lit(hi)}'


def merge_duplicate_labels(rows):
    """A label printed twice on one chart becomes one row spanning both, flagged for a human to check."""
    merged, order = {}, []
    for r in rows:
        key = r['label']
        if key not in merged:
            merged[key] = dict(r)
            order.append(key)
            continue
        m = merged[key]
        for meas in MEASURES:
            a, b = m.get(meas), r.get(meas)
            if a is None or b is None:
                m[meas] = a if b is None else b
            else:
                m[meas] = [min(a[0], b[0]), max(a[1], b[1])]
        al = dict(m.get('aliases') or {})
        for k, v in (r.get('aliases') or {}).items():
            al[k] = v if k not in al or al[k] == v else f'{al[k]}/{v}'
        m['aliases'] = al
        m['_dup_note'] = 'The chart lists this label more than once; the rows were merged into one range. Check the source before verifying.'
    return [merged[k] for k in order]


def main():
    files = sorted(glob.glob(os.path.join(SRC, '*.json')))
    out = ['-- Generated by supabase/scripts/build_seed.py from data/charts/*.json. Do not edit by hand.',
           '-- All charts are drafts. Verify each against its source_url, then:',
           "--   update size_charts set status = 'verified', verified_by = 'you', verified_at = now() where id = '…';",
           'begin;']
    charts = rows = 0
    for f in files:
        d = json.load(open(f))
        bid = d['brand_id']
        aliases = sorted({a.lower() for a in [d['brand_name']] + d.get('aliases', [])})
        out.append(f"insert into public.brands (id, name, aliases, website) values ({lit(bid)}, {lit(d['brand_name'])}, "
                   f"array[{', '.join(lit(a) for a in aliases)}]::text[], {lit(d.get('website'))}) "
                   "on conflict (id) do update set name = excluded.name, aliases = excluded.aliases, website = excluded.website;")
        for c in d['charts']:
            cid = str(uuid.uuid5(NS, '|'.join([bid, c['category'], c.get('fit_line') or '', c['source_url']])))
            notes = d.get('problems') or None
            out.append(
                'insert into public.size_charts (id, brand_id, gender, category, fit_line, measurement_basis, basis_evidence, unit, '
                'size_system, source_url, source_type, retailer, retrieved_on, fit_advice, status, notes) values ('
                f"{lit(cid)}, {lit(bid)}, {lit(c.get('gender', 'women'))}, {lit(c['category'])}, {lit(c.get('fit_line'))}, "
                f"{lit(c.get('measurement_basis'))}, {lit(c.get('basis_evidence'))}, {lit(c.get('unit'))}, {lit(c['size_system'])}, "
                f"{lit(c['source_url'])}, {lit(c['source_type'])}, {lit(c.get('retailer'))}, {lit(c['retrieved_on'])}, "
                f"{lit(c.get('fit_advice'))}, 'draft', {lit(notes)}) "
                'on conflict (id) do update set measurement_basis = excluded.measurement_basis, basis_evidence = excluded.basis_evidence, '
                'unit = excluded.unit, size_system = excluded.size_system, retrieved_on = excluded.retrieved_on, '
                'fit_advice = excluded.fit_advice, notes = excluded.notes;')
            out.append(f"delete from public.size_chart_rows where chart_id = {lit(cid)};")
            charts += 1
            for i, r in enumerate(merge_duplicate_labels(c['rows'])):
                extra = {k: v for k, v in r.items() if k not in MEASURES and k not in ('label', 'aliases', '_dup_note')}
                note = SUSPECT.get((bid, c['category'], c.get('fit_line'), r['label'])) or r.get('_dup_note')
                out.append(
                    'insert into public.size_chart_rows (chart_id, position, label, aliases, bust_min, bust_max, waist_min, waist_max, '
                    'hip_min, hip_max, inseam_min, inseam_max, foot_length_min, foot_length_max, extra, suspect, suspect_note) values ('
                    f"{lit(cid)}, {i}, {lit(r['label'])}, {jsonb(r.get('aliases') or {})}, "
                    + ', '.join(rng(r.get(m)) for m in MEASURES)
                    + f", {jsonb(extra)}, {lit(note is not None)}, {lit(note)});")
                rows += 1
    out.append('commit;')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as fh:
        fh.write('\n'.join(out) + '\n')
    print(f'{len(files)} brands, {charts} charts, {rows} rows → {os.path.relpath(OUT, ROOT)}')


if __name__ == '__main__':
    main()
